name = "SymbolicIntegration"
uuid = "315ce56f-eed0-411d-ab8a-2fbdf9327b51"
authors = ["HaraldHofstaetter <hofi@harald-hofstaetter.at>"]
version = "0.1.0"

[deps]
AbstractAlgebra = "c3fe647b-3220-5bb0-a1ea-a7954cac585d"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Nemo = "2edaba10-b0f1-5616-af89-8c11ac63239a"
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"

[compat]
AbstractAlgebra = "0.23.0"
Nemo = "0.28.0"
SymbolicUtils = "0.18, 0.19"
julia = "1.7"