name = "SymbolicIntegration"
uuid = "315ce56f-eed0-411d-ab8a-2fbdf9327b51"
authors = ["HaraldHofstaetter <hofi@harald-hofstaetter.at>"]
version = "0.1.0"

[deps]
AbstractAlgebra = "c3fe647b-3220-5bb0-a1ea-a7954cac585d"
