name = "SymbolicIntegration"
uuid = "315ce56f-eed0-411d-ab8a-2fbdf9327b51"
authors = ["HaraldHofstaetter <hofi@harald-hofstaetter.at>", "Chris Rackauckas <accounts@chrisrackauckas.com>", "JuliaSymbolics contributors"]
version = "2.0.0"
description = "Symbolic integration algorithms for Julia"
repository = "https://github.com/JuliaSymbolics/SymbolicIntegration.jl"
license = "MIT"
keywords = ["symbolic", "integration", "mathematics", "computer-algebra"]

[deps]
AbstractAlgebra = "c3fe647b-3220-5bb0-a1ea-a7954cac585d"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Nemo = "2edaba10-b0f1-5616-af89-8c11ac63239a"
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Elliptic = "b305315f-e792-5b7a-8f41-49f472929428"
FresnelIntegrals = "88497964-e39a-11e9-0fb5-b1bf0ffe80fe"
HypergeometricFunctions = "34004b35-14d8-5ef3-9330-4cdb6864b03a"
PolyLog = "85e3b03c-9856-11eb-0374-4dc1f8670e7f"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[compat]
AbstractAlgebra = "0.46"
Nemo = "0.51"
SymbolicUtils = "3"
Symbolics = "6"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
