name: CI
on:
  push:
    branches:
      - main
    tags: ['*']
  pull_request:
  workflow_dispatch:
concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    permissions: # needed to allow julia-actions/cache to proactively delete old caches that it has created
      actions: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.11'
          - 'pre'
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v5
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@v1
      - name: Run tests and count rules
        if: matrix.version == '1.11' && matrix.os == 'ubuntu-latest'
        run: |
          julia --project=. -e '
            using Pkg
            Pkg.test()
            
            # Count rules after tests (package already loaded)
            using SymbolicIntegration
            rules_count = length(SymbolicIntegration.RULES)
            println("::notice title=Rules Count::Total integration rules: $rules_count")
            
            # Set output for next step
            open(ENV["GITHUB_OUTPUT"], "a") do f
                println(f, "rules_count=$rules_count")
            end
          '
        id: count_rules
          
      - name: Update repository variable
        if: matrix.version == '1.11' && matrix.os == 'ubuntu-latest' && github.ref == 'refs/heads/main'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Create or update repository variable
          curl -L \
            -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/actions/variables/RULES_COUNT \
            -d "{\"name\":\"RULES_COUNT\",\"value\":\"${{ steps.count_rules.outputs.rules_count }}\"}" \
            || \
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/actions/variables \
            -d "{\"name\":\"RULES_COUNT\",\"value\":\"${{ steps.count_rules.outputs.rules_count }}\"}"
          
      - name: Run tests (other configurations)  
        if: !(matrix.version == '1.11' && matrix.os == 'ubuntu-latest')
        uses: julia-actions/julia-runtest@v1
